name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Backend - Build
        run: docker build . --target backend-builder

      - name: Backend - Test
        run: docker build . --target backend-test

      - name: Frontend - Prepare
        run: docker build . --target frontend-builder

      - name: Frontend - Checks
        run: docker build . --target frontend-check

      - name: Frontend - Build
        run: docker build . --target frontend-publish

      - name: Desktop - Build
        run: docker build . --target desktop-builder
